# Importing Libraries

In [2]:
import numpy as np #Linear Algebra
import pandas as pd #data processing
import matplotlib.pyplot as plt #data visualization
import seaborn as sns #data visualization

## Loading data

In [89]:
data = pd.read_csv("BSE_30_Data.csv")

In [91]:
data.head()

,Symbol,Date,Open,High,Low,Close,Adj Close,Volume
0,ADANIPORTS,05-06-2008,150.000000,153.570007,147.820007,151.149994,134.313477,1782030.0
1,ADANIPORTS,05-07-2008,152.000000,154.460007,150.240005,153.309998,136.232864,1180015.0
2,ADANIPORTS,05-08-2008,152.199997,156.759995,150.199997,155.889999,138.525497,1856245.0
3,ADANIPORTS,05-09-2008,155.000000,160.600006,154.210007,156.520004,139.085312,3251375.0
4,ADANIPORTS,05-12-2008,156.000000,163.479996,151.000000,162.500000,144.399170,5031635.0

In [92]:
data_groupby = data.groupby('Symbol')

In [93]:
data_groupby.describe()

              Open                                                       \
             count         mean            std         min          25%
Symbol
ADANIPORTS  2461.0   201.850301      97.525373   50.220001   130.000000
ASIANPAINT  2462.0   642.564641    4871.775778   68.089996   261.105011
AXISBANK    2462.0   328.066146     150.247692   57.400002   213.554996
BAJAJ-AUTO  2446.0  1818.840990     828.080103  147.324997  1355.199982
BHARTIARTL  2461.0   352.785991      49.972736  240.500000   318.000000
COALINDIA   1846.0   324.848022      41.294084  237.000000   294.000000
DRREDDY     2461.0  2079.514690     944.250558  372.000000  1490.000000
HDFC        2461.0  7772.363784  340000.294717  227.399994   638.299988
HDFCBANK    2461.0  2604.942906   90515.997282  158.000000   435.000000
HEROMOTOCO  2462.0  2232.594030     815.428843  652.000000  1730.774994
HINDUNILVR  2461.0   595.378972     322.402019  194.449997   282.000000
ICICIBANK   2462.0   204.572792      63.987478   48.181801   161.204754
INDUSINDBK  2461.0   598.082182     498.604229   26.549999   235.399994
INFY        2462.0   788.276797     240.461361  275.000000   612.565750
ITC         2461.0   211.851073    1711.948319   52.016701   112.500000
KOTAKBANK   2461.0   447.749289     289.852713   53.000000   210.899994
LT          2461.0   815.309731     248.733140  251.156006   637.911011
M&M         2462.0   454.995621     193.810162   62.500000   327.500000
MARUTI      2461.0  4387.345368   77634.207353  428.399994  1236.000000
ONGC        2461.0   187.339600      33.515604  104.616997   170.667007
POWERGRID   2461.0   128.183889      37.479911   60.049999   101.500000
RELIANCE    2461.0   505.305242     137.142478  252.500000   425.000000
SBIN        2462.0   224.812540      53.252699   90.699997   186.000000
SUNPHARMA   2461.0   458.934383     271.832520   97.610001   210.000000
TATAMOTORS  2461.0   299.384011     148.743168   24.141701   177.104996
TATAMTRDVR  2319.0   194.597740      90.078236   25.400000   122.299999
TATASTEEL   2462.0   427.659858     140.715839  141.009995   329.551743
TCS         2461.0  1643.415065     840.045820  225.000000   990.049988
WIPRO       2461.0   592.841382   18357.333676   59.999901   191.100006
YESBANK     2461.0   121.490000      95.757639    8.490000    55.400002

                                                      High               ...  \
                    50%          75%           max   count         mean  ...
Symbol                                                                   ...
ADANIPORTS   154.199997   283.899994  4.490000e+02  2461.0   205.175567  ...
ASIANPAINT   456.294999   859.500000  2.416330e+05  2462.0   648.647644  ...
AXISBANK     268.000000   488.887497  6.504000e+02  2462.0   332.625602  ...
BAJAJ-AUTO  1895.000000  2473.149902  3.413000e+03  2446.0  1840.468203  ...
BHARTIARTL   345.399994   385.000000  5.440000e+02  2461.0   358.203881  ...
COALINDIA    322.875000   355.700012  4.440000e+02  1846.0   328.770070  ...
DRREDDY     1995.050049  2873.600098  4.373000e+03  2461.0  2103.405566  ...
HDFC         804.099976  1226.000000  1.686780e+07  2461.0   965.640434  ...
HDFCBANK     651.000000  1066.099976  4.491080e+06  2461.0   787.619699  ...
HEROMOTOCO  2019.500000  2824.437561  4.200000e+03  2462.0  2259.701014  ...
HINDUNILVR   555.000000   848.849976  1.510000e+03  2461.0   601.676046  ...
ICICIBANK    197.945503   254.965500  3.600000e+02  2462.0   207.378247  ...
INDUSINDBK   414.000000   924.000000  1.899000e+03  2461.0   605.678667  ...
INFY         759.937500   990.000000  1.270000e+03  2462.0   796.789370  ...
ITC          203.332993   234.667007  8.502780e+04  2461.0   213.748821  ...
KOTAKBANK    332.500000   685.000000  1.263000e+03  2461.0   453.090666  ...
LT           747.111023  1006.630005  1.455000e+03  2461.0   825.234204  ...
M&M          446.862503   630.899994  8.800000e+02  2462.0   460.727387  ...
MARUTI      1542.000000  4036.750000  3.852390e+06  2461.0  2856.336817  ...
ONGC         185.332993   203.000000  3.133330e+02  2461.0   189.790758  ...
POWERGRID    111.650002   142.500000  2.260000e+02  2461.0   129.710626  ...
RELIANCE     486.500000   528.375000  9.882500e+02  2461.0   511.483292  ...
SBIN         227.635002   263.774994  3.515000e+02  2462.0   227.805790  ...
SUNPHARMA    472.500000   681.000000  1.180000e+03  2461.0   464.552202  ...
TATAMOTORS   294.350006   424.200012  5.995840e+02  2461.0   303.596994  ...
TATAMTRDVR   173.199997   272.800003  3.890000e+02  2319.0   197.399711  ...
TATASTEEL    409.691986   533.695236  8.765500e+02  2462.0   434.270255  ...
TCS         1494.000000  2470.000000  3.540000e+03  2461.0  1661.807921  ...
WIPRO        224.000000   275.799988  9.108970e+05  2461.0   595.590573  ...
YESBANK       75.800003   164.500000  3.799500e+02  2461.0   123.250199  ...

              Adj Close               Volume                                   \
                    75%          max   count          mean           std  min
Symbol
ADANIPORTS   281.410828   448.200012  2461.0  6.102323e+05  1.362010e+06  0.0
ASIANPAINT   841.679779  1253.037231  2462.0  1.272624e+05  2.864074e+05  0.0
AXISBANK     481.409874   630.680115  2462.0  1.646189e+06  6.213174e+06  0.0
BAJAJ-AUTO  2362.433593  3409.500000  2446.0  5.631276e+04  1.676051e+05  0.0
BHARTIARTL   375.478821   539.598877  2461.0  8.639073e+05  6.885412e+06  0.0
COALINDIA    275.965203   358.187164  1846.0  5.748495e+05  4.550789e+06  0.0
DRREDDY     2815.606934  4256.671387  2461.0  4.309090e+04  7.134811e+04  0.0
HDFC        1196.343750  1963.763916  2461.0  3.905815e+05  1.056233e+06  0.0
HDFCBANK    1046.849487  2006.349976  2461.0  4.004611e+05  1.501936e+06  0.0
HEROMOTOCO  2638.804871  3985.463867  2462.0  5.200792e+04  1.079100e+05  0.0
HINDUNILVR   820.279541  1509.050049  2461.0  2.303232e+05  3.583037e+05  0.0
ICICIBANK    245.254826   362.049988  2462.0  3.958186e+06  6.312840e+06  0.0
INDUSINDBK   913.813965  1898.199951  2461.0  2.122095e+05  4.467344e+05  0.0
INFY         947.263900  1203.725342  2462.0  5.077490e+05  7.051639e+05  0.0
ITC          219.780457   342.299988  2461.0  1.124150e+06  1.361497e+06  0.0
KOTAKBANK    683.579773  1257.250000  2461.0  5.581752e+05  1.848810e+06  0.0
LT           961.688843  1455.800049  2461.0  6.998440e+05  1.077089e+06  0.0
M&M          603.414169   872.650024  2462.0  3.529246e+05  6.750681e+05  0.0
MARUTI      3963.238770  9804.500000  2461.0  9.072945e+04  1.044838e+05  0.0
ONGC         175.041168   261.485962  2461.0  9.579163e+05  1.141051e+06  0.0
POWERGRID    135.108673   219.568817  2461.0  6.499244e+05  2.677777e+06  0.0
RELIANCE     482.912567   994.750000  2461.0  2.752583e+06  2.748189e+07  0.0
SBIN         248.628677   337.399994  2462.0  4.315084e+06  3.435711e+06  0.0
SUNPHARMA    674.711304  1155.346191  2461.0  3.155059e+05  6.499564e+05  0.0
TATAMOTORS   422.649994   598.451050  2461.0  2.060176e+06  5.484895e+06  0.0
TATAMTRDVR   271.693955   387.875793  2319.0  2.885267e+05  7.075570e+05  0.0
TATASTEEL    461.409882   746.210999  2462.0  1.409363e+06  1.272559e+06  0.0
TCS         2375.596680  3540.350098  2461.0  2.198629e+05  2.953515e+05  0.0
WIPRO        261.456848   330.821350  2461.0  4.434375e+05  6.372397e+05  0.0
YESBANK      145.624405   377.000000  2461.0  2.427255e+06  5.762929e+06  0.0


                   25%        50%         75%          max
Symbol
ADANIPORTS   150596.00   266229.0   559965.00   32790510.0
ASIANPAINT    40519.75    67460.5   114874.00    6309900.0
AXISBANK     497337.25   838394.5  1566945.00  263413195.0
BAJAJ-AUTO    15400.50    25311.0    46566.75    4607686.0
BHARTIARTL   175600.00   314991.0   712347.00  279514756.0
COALINDIA    163784.00   265440.5   477650.25  192871282.0
DRREDDY       13382.00    22711.0    44056.00    1159551.0
HDFC          70952.00   146213.0   347505.00   25123026.0
HDFCBANK      83354.00   177713.0   366720.00   68357010.0
HEROMOTOCO    16985.50    29245.5    52997.75    3085587.0
HINDUNILVR    73718.00   125606.0   255122.00    9276199.0
ICICIBANK   1022381.00  1910897.0  3748658.75   83811772.0
INDUSINDBK    45041.00    90973.0   201073.00   10487630.0
INFY         173098.00   298324.0   574799.00    8980928.0
ITC          429328.00   687471.0  1296093.00   16864668.0
KOTAKBANK     61444.00   122438.0   393710.00   53431112.0
LT           242457.00   400550.0   749455.00   35944390.0
M&M          105212.50   203355.5   440035.00   27011638.0
MARUTI        32746.00    55522.0   105772.00    1451146.0
ONGC         352116.00   589419.0  1095882.00   21303414.0
POWERGRID    126354.00   247349.0   656791.00   98371545.0
RELIANCE     542180.00   925542.0  1842598.00  794622760.0
SBIN        1912608.25  3307640.5  5637952.50   27208290.0
SUNPHARMA    111852.00   187625.0   335703.00   16095115.0
TATAMOTORS   507880.00   999991.0  2319491.00  221371337.0
TATAMTRDVR    66958.50   120580.0   242635.50   13199130.0
TATASTEEL    669942.50  1002166.0  1636235.75   15889804.0
TCS           55548.00   111192.0   245845.00    3935009.0
WIPRO        149456.00   254645.0   506548.00   13252240.0
YESBANK      872550.00  1374085.0  2270055.00  209698210.0

[30 rows x 48 columns]

## Splitting Data

In [94]:
data_pivot = data.pivot_table(index=['Symbol', 'Date'] )
data_pivot

                        Adj Close       Close        High         Low  \
Symbol     Date
ADANIPORTS 01-01-2013  134.511597  137.500000  137.949997  135.399994
           01-01-2014  153.859589  156.149994  157.800003  155.800003
           01-01-2015  316.161407  319.649994  322.600006  316.250000
           01-01-2016  265.418854  267.500000  268.200012  260.200012
           01-01-2018  400.399994  400.399994  406.600006  398.799988
...                           ...         ...         ...         ...
YESBANK    9/30/2011    38.898773   54.500000   56.299999   54.029999
           9/30/2013    46.249695   57.500000   59.740002   57.240002
           9/30/2014    96.742287  111.699997  114.379997  110.849998
           9/30/2015   133.233475  145.919998  150.820007  144.759995
           9/30/2016   240.765930  250.850006  251.750000  242.710007

                             Open     Volume
Symbol     Date
ADANIPORTS 01-01-2013  136.449997    82750.0
           01-01-2014  155.850006   141907.0
           01-01-2015  319.000000   210257.0
           01-01-2016  260.450012   200186.0
           01-01-2018  405.950012   124121.0
...                           ...        ...
YESBANK    9/30/2011    54.880001  1168325.0
           9/30/2013    59.740002  8875440.0
           9/30/2014   113.599998  1373085.0
           9/30/2015   149.070007  2437990.0
           9/30/2016   246.800003  1318765.0

[73066 rows x 6 columns]

In [62]:
data_ADANIPORTS = data_pivot.loc['ADANIPORTS']
data_ADANIPORTS.to_csv('data_ADANIPORTS.csv')

data_ADANIPORTS = data_pivot.loc['ADANIPORTS']
data_ADANIPORTS.to_csv('data_ADANIPORTS.csv')

## Indexes

In [78]:
#Getting Indexes
index = set()
for i in data['Symbol']:
    index.add(i)
index

{'ADANIPORTS',
 'ASIANPAINT',
 'AXISBANK',
 'BAJAJ-AUTO',
 'BHARTIARTL',
 'COALINDIA',
 'DRREDDY',
 'HDFC',
 'HDFCBANK',
 'HEROMOTOCO',
 'HINDUNILVR',
 'ICICIBANK',
 'INDUSINDBK',
 'INFY',
 'ITC',
 'KOTAKBANK',
 'LT',
 'M&M',
 'MARUTI',
 'ONGC',
 'POWERGRID',
 'RELIANCE',
 'SBIN',
 'SUNPHARMA',
 'TATAMOTORS',
 'TATAMTRDVR',
 'TATASTEEL',
 'TCS',
 'WIPRO',
 'YESBANK'}